name: Upload Code Coverage

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        working-directory: backend
        run: npm ci
      
      - name: Run backend tests
        working-directory: backend
        run: npm run test -- --coverage
        env:
          CI: true

  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      
      - name: Run frontend tests
        working-directory: frontend
        run: npm run test -- --coverage
        env:
          CI: true

  upload-coverage:
    needs: [test_backend, test_frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Upload Backend Coverage Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./backend/coverage

      - name: Upload Frontend Coverage Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./frontend/coverage
