name: Lint Codebase

on:
    push:
        branches:
            - "*" # All branches

env:
    JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
    DB_TYPE: ${{ secrets.DB_TYPE }}
    DB_HOST: ${{ secrets.DB_HOST }}
    DB_PORT: ${{ secrets.DB_PORT }}
    DB_USERNAME: ${{ secrets.DB_USERNAME }}
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    DB_NAME: ${{ secrets.DB_NAME }}
    PEPPER: ${{ secrets.PEPPER }}
    TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
    TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
    TEST_SALT: ${{ secrets.TEST_SALT }}
    DB_TEST_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
    AUTH_BEARER: ${{ secrets.AUTH_BEARER }}
    TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}

jobs:
    lint_backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16.x"
                  cache: "npm"
                  cache-dependency-path: backend/package-lock.json

            - name: Install dependencies
              working-directory: backend
              run: npm install

            - name: Format code
              working-directory: backend
              run: npm run format

    lint_frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16.x"
                  cache: "npm"
                  cache-dependency-path: frontend/package-lock.json

            - name: Install dependencies
              working-directory: frontend
              run: npm install

            - name: Format code
              working-directory: frontend
              run: npm run format
