name: Test Codebase

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
        
      - name: Install dependencies
        working-directory: backend
        run: npm install
    
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Serve the application
        working-directory: frontend
        run: npm run start &
        
      - name: Wait for the application to start
        working-directory: frontend
        run: sleep 5s

  run_tests:
    runs-on: ubuntu-latest
    needs: [build_backend, build_frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # - name: Run backend tests
      #   working-directory: backend
      #   run: npm run test

      - name: Run frontend tests
        working-directory: frontend
        run: npm run test