name: Test Integration

on:
    push:
        branches: ["test", "integration/*", "codecov"]
    pull_request:
        branches: ["test", "integration/*", "codecov"]

env:
    JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
    DB_TYPE: ${{ secrets.DB_TYPE }}
    DB_HOST: ${{ secrets.DB_HOST }}
    DB_PORT: ${{ secrets.DB_PORT }}
    DB_USERNAME: ${{ secrets.DB_USERNAME }}
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    DB_NAME: ${{ secrets.DB_NAME }}
    PEPPER: ${{ secrets.PEPPER }}
    TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
    TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
    TEST_SALT: ${{ secrets.TEST_SALT }}
    DB_TEST_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
    AUTH_BEARER: ${{ secrets.AUTH_BEARER }}
    TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
    AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
    AWS_S3_BUCKET_REGION: ${{ secrets.AWS_S3_BUCKET_REGION }}
    AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
    AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}

jobs:
    test_integration:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16.x"
                  cache: "npm"
                  cache-dependency-path: backend/package-lock.json

            - name: Install dependencies
              working-directory: backend
              run: npm install

            - name: Run integration tests
              working-directory: backend
              run: npm run test:e2e
